import { useState } from 'react'
import { pdf } from '@react-pdf/renderer'
import { createElement } from 'react'
import { supabase } from '../lib/supabase'
import { withTimeout } from '../lib/withTimeout'
import { logActivity } from '../lib/logActivity'
import { invalidateKeys } from '../lib/cache'
import type { Phone, Profile, Receipt, SaleFormData } from '../types'
import toast from 'react-hot-toast'

// Lazy import to avoid circular refs
let ReceiptDocumentComponent: React.ComponentType<{ data: ReceiptPdfData }> | null = null
async function getReceiptDocument() {
  if (!ReceiptDocumentComponent) {
    const mod = await import('../components/shared/ReceiptDocument')
    ReceiptDocumentComponent = mod.default
  }
  return ReceiptDocumentComponent
}

export interface ReceiptPdfData {
  receiptNumber:  string
  generatedAt:    string
  agentName:      string
  agentId:        string
  buyerName:      string
  buyerPhone:     string
  phoneModel:     string
  imei:           string
  barcode:        string
  sellingPrice:   number
  paymentMethod:  string
}

interface SaleResult {
  receipt: Receipt
  pdfBlob: Blob
  pdfUrl:  string
}

export function useSaleReceipt() {
  const [loading, setLoading] = useState(false)

  async function completeSale(
    phone:  Phone,
    actor:  Profile,
    form:   SaleFormData,
  ): Promise<SaleResult | null> {
    setLoading(true)
    try {
      const now   = new Date().toISOString()
      const price = parseFloat(form.agreedPrice)

      // 1. Insert sale record
      const { data: sale, error: saleErr } = await withTimeout(
        supabase.from('sales').insert({
          phone_id:       phone.id,
          sold_by:        actor.id,
          sold_at:        now,
          buyer_name:     form.buyerName,
          buyer_phone:    form.buyerPhone,
          agreed_price:   price,
          payment_method: form.paymentMethod,
        }).select().single(),
        12000,
      )
      if (saleErr || !sale) throw saleErr ?? new Error('Sale insert failed')

      // 2. Update phone status
      const { error: phoneErr } = await withTimeout(
        supabase.from('phones').update({ status: 'sold', sold_at: now }).eq('id', phone.id),
        12000,
      )
      if (phoneErr) throw phoneErr

      // 3. Insert receipt row (receipt_number auto-generated by DB sequence)
      const { data: receipt, error: recErr } = await withTimeout(
        supabase.from('receipts').insert({
          sale_id:        sale.id,
          phone_id:       phone.id,
          agent_id:       actor.id,
          buyer_name:     form.buyerName,
          buyer_phone:    form.buyerPhone,
          selling_price:  price,
          payment_method: form.paymentMethod,
        }).select().single(),
        12000,
      )
      if (recErr || !receipt) throw recErr ?? new Error('Receipt insert failed')

      // 4. Generate PDF in-browser
      const pdfData: ReceiptPdfData = {
        receiptNumber: receipt.receipt_number,
        generatedAt:   receipt.generated_at ?? now,
        agentName:     actor.full_name,
        agentId:       actor.id.slice(0, 8).toUpperCase(),
        buyerName:     form.buyerName,
        buyerPhone:    form.buyerPhone,
        phoneModel:    phone.model,
        imei:          phone.imei ?? '',
        barcode:       phone.barcode ?? '',
        sellingPrice:  price,
        paymentMethod: form.paymentMethod,
      }

      const DocComponent = await getReceiptDocument()
      // @react-pdf/renderer's pdf() expects a Document element; we cast to bypass the type mismatch
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const element = createElement(DocComponent as any, { data: pdfData }) as any
      const pdfBlob = await pdf(element).toBlob()

      // 5. Upload PDF to Supabase Storage
      const fileName = `${receipt.receipt_number}.pdf`
      const { error: uploadErr } = await supabase.storage
        .from('receipts')
        .upload(fileName, pdfBlob, { contentType: 'application/pdf', upsert: true })

      let pdfUrl = ''
      if (!uploadErr) {
        const { data: urlData } = supabase.storage.from('receipts').getPublicUrl(fileName)
        pdfUrl = urlData.publicUrl
        await withTimeout(
          supabase.from('receipts').update({ pdf_url: pdfUrl }).eq('id', receipt.id),
          8000,
        )
      }

      const phoneLabel = `${phone.model} / ${phone.imei ?? phone.barcode ?? phone.serial_number}`

      // 6 & 7. Log to activity_log (fire-and-forget — does not block)
      logActivity({
        actor_id:     actor.id,
        actor_name:   actor.full_name,
        role:         actor.role,
        action_type:  'SALE_RECORDED',
        entity_type:  'phone',
        entity_id:    phone.id,
        entity_label: phoneLabel,
        meta:         {
          model:          phone.model,
          imei:           phone.imei,
          price,
          payment:        form.paymentMethod,
          buyer:          form.buyerName,
          receipt_number: receipt.receipt_number,
        },
        agent_id:     actor.role === 'agent'     ? actor.id : null,
        team_lead_id: actor.role === 'team_lead' ? actor.id : null,
      })
      logActivity({
        actor_id:     actor.id,
        actor_name:   actor.full_name,
        role:         actor.role,
        action_type:  'RECEIPT_GENERATED',
        entity_type:  'receipt',
        entity_id:    receipt.id,
        entity_label: receipt.receipt_number,
        meta:         { pdf_url: pdfUrl },
        agent_id:     actor.role === 'agent'     ? actor.id : null,
        team_lead_id: actor.role === 'team_lead' ? actor.id : null,
      })

      // 8. Send notifications to admin + team lead
      await supabase.rpc('notify_on_sale', {
        p_sale_id:    sale.id,
        p_agent_id:   actor.id,
        p_agent_name: actor.full_name,
        p_phone_label: phoneLabel,
        p_amount:     price,
        p_payment:    form.paymentMethod,
      })

      // 9. Invalidate caches
      await invalidateKeys('inventory:all', `sales:summary:${actor.id}:${now.slice(0, 10)}`)

      toast.success('Sale recorded!')
      return { receipt: { ...receipt, pdf_url: pdfUrl }, pdfBlob, pdfUrl }
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'Unknown error'
      toast.error(`Sale failed: ${msg}`)
      return null
    } finally {
      setLoading(false)
    }
  }

  return { completeSale, loading }
}
